INSERT [dbo].[Localization_Culture] ([Id], [Name]) VALUES ('zh-TW', N'Traditional Chinese')
GO

INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Register', N'註冊,')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Hello {0}!', N'農民Go會員，您好!')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Log in', N'登出')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Log off', N'登出' )
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'The Email field is required.', N'請填電子郵件')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Email', N'電子郵件' )
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'User List', N'使用者清單')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Remember me?', N'記住我?')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Password', N'密碼')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Use a local account to log in.', N'使用本地帳號登入.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Register as a new user?', N'新用戶註冊?')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Forgot your password?', N'忘記密碼?');
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Use another service to log in.', N'其他平台登入.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Full name', N'全名')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Confirm password', N'密碼確定')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create a new account.', N'新增帳號.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'All', N'全部')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Home', N'首頁')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Add to cart', N'加入購物車')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product detail', N'产品详细信息')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product specification', N'产品规格')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Rate this product', N'评价该产品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Review comment', N'回顾评论')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Review title', N'评论标题')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Posted by', N'发表于')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Submit review', N'提交评论')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'You have', N'你有.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'products in your cart', N'购物车的产品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Continue shopping', N'继续购买')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'View cart', N'查看购物车')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'The product has been added to your cart', N'该产品已被添加到您的购物车.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Cart subtotal', N'购物车小计')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Shopping Cart', N'购物车')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product', N'产品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Price', N'价格')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Quantity', N'数量')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'There are no items in this cart.', N'此购物车中没有商品.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Go to shopping', N'开始购买')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Order summary', N'订单总结')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Subtotal', N'小计');
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Process to Checkout', N'进行结算')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Shipping address', N'邮寄地址')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Add another address', N'添加地址')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Contact name', N'联系人姓名')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Address', N'地址');
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'State or Province', N'州或省')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'District', N'区')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Phone', N'手机号码')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Order', N'订购')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'products', N'商品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'reviews', N'评论')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Add Review', N'添加评论')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Customer reviews', N'顾客评论')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Your review will be shown within the next 24h.', N'您的评论将在24小时内显示.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Thank you {0} for your review', N'谢谢您的评论.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Rating average', N'平均评分')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'stars', N'开始')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Filter by', N'过滤')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Category', N'类别')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Brand', N'品牌')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Sort by:', N'排序方式 :')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'results', N'结果')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'View options', N'查看选项')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Associate your {0} account.', N'{0} 联结账号.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Users', N'用户')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Vendors', N'供应商')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Reviews', N'评测')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Products', N'产品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Categories', N'分类')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Brands', N'品牌')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Options', N'产品选项')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Attribute', N'产品属性')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Attribute Groups', N'产品属性组')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Templates', N'产品模板')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Sales', N'减价出售')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Orders', N'订货')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Content Management', N'内容管理')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Pages', N'页面')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Widgets', N'小工具')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'System', N'系统')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Configuration', N'设置')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Translations', N'翻译')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Dashboard', N'仪表板')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Incomplete orders', N'订单未完成')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Pending reviews', N'待审查')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Most searched keywords', N'大多数搜索关键字')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Most viewed products', N'最受欢迎的产品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'OrderId', N'排序')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Order Status', N'订单状态')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Customer', N'客户')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Created On', N'创建于')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'SubTotal', N'小计')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Actions', N'操作')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Site', N'位置')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Catalog', N'目录')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Title', N'标题')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Comment', N'评论')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Status', N'状态')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Rating', N'评分')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Keyword', N'关键词')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Count', N'计数')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create User', N'创建用户')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'FullName', N'全名')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Roles', N'角色')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit User', N'编辑用户')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Manager of Vendor', N'供应商管理')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Save', N'保存')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Cancel', N'取消')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Phone Number', N'电话号码')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Vendor', N'创建供应商')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Is Active', N'活跃.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Vendor', N'编辑供应商')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Managers', N'管理员')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Description', N'描述')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Pending', N'有待')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Approved', N'批准')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Not Approved', N'不批准')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Approve', N'批准')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Product', N'创建产品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Has Options', N'有选项')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Is Visible Individually', N'单独可见.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Is Featured', N'精品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Is Allowed To Order', N'允许订购.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Is Called For Pricing', N'定价')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Stock Quantity', N'库存数量')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Is Published', N'发布')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Yes', N'确定')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'No', N'否!')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Product', N'编辑产品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Name', N'产品名称')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Short Description', N'简短描述')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Specification', N'规范')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Old Price', N'原价')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Special Price', N'特价')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Special Price Start', N'特价开始')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Special Price End', N'特价结束')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Thumbnail', N'缩略图')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Images', N'产品图片')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Documents', N'产品文件')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Out Of Stock', N'断货')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Available Options', N'可用选项')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Add Option', N'添加选项')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Option Values', N'选项值')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Delete Option', N'删除选项')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Generate Combinations', N'生成组合')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Variations', N'产品型号')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Option Combinations', N'选项组合')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Images', N'图片')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Apply', N'提供')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Available Attributes', N'可用属性')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Add Attribute', N'添加属性')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Attributes', N'产品属性')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Attribute Name', N'属性名称')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Value', N'值')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'General Information', N'一般信息')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Category Mapping', N'类别映射')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Related Products', N'相关产品')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Manage Related Products', N'相关产品管理')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Category', N'创建类别')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Category', N'编辑类别')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Brand', N'创建您的品牌')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Brand', N'修改您的品牌')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Name', N'名称')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Parent Category', N'顶级类别')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Group', N'组')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Product Attribute', N'创建产品属性')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Product Attribute', N'编辑产品属性')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Product Attribute Group', N'创建产品属性组')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Product Attribute Group', N'编辑产品属性组')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Product Option', N'产品创建选项')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Product Option', N'编辑产品选项')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Product Display Widget', N'创建产品展示小部件')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Product Display Widget', N'编辑产品展示小部件')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Widget Name', N'小工具名称')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Widget Zone', N'小部件区域')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Publish Start', N'开始发布')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Publish End', N'发布结束')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Number of Products', N'产品数量')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Order By', N'按排序')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Product Template', N'创建产品模板')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Product Template', N'编辑产品模板')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Added Attributes', N'添加属性')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Back', N'返回')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Order Detail', N'订单详情')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Order Information', N'订单信息')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Change', N'更改')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Product Information', N'产品信息')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Shipping Information', N'运送信息')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Application Settings', N'应用设置')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Page', N'创建页面')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Page', N'编辑页面')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Body', N'体')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Account Dashboard', N'帐户信息中心')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Account Information', N'帐户信息')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit', N'编辑')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Security', N'安全')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create', N'创建')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'External Logins', N'外部登录')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Manage', N'管理')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Default shipping address', N'默认邮寄地址')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Manage address', N'地址管理')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'You don''t have any default address', N'您没有任何的默认地址.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Order History', N'订单记录')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Address Book', N'地址簿')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Add Address', N'添加地址')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Delete', N'取消')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Set as default shipping address', N'设置为默认邮寄地址')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Edit Address', N'编辑地址')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Create Address', N'创建地址')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Your account', N'您的帐号')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Date', N'日期')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Add to Compare', N'加入对比')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Not available', N'无法使用')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'You save', N'您保存')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Submit', N'提交')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'All Categories', N'所有类别')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('zh-TW', N'Search here...', N'在这里搜索')
GO
